export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "FAIL";
export const GET_DAY = "GET_DAY";
export const GET_DAY_SUCCESS = "GET_DAY_SUCCESS";
export const GET_DAY_FAIL = "GET_DAY_FAIL";
export const SELECT_DAY = "SELECT_DAY";
export const NEXT_DAY = "NEXT_DAY";
export const GET_TRIPS = "GET_TRIPS";
export const GET_TRIPS_SUCCESS = "GET_TRIPS_SUCCESS";
export const GET_TRIPS_FAIL = "GET_TRIPS_FAIL";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAIL = "AUTHENTICATION_FAIL";
export const AUTHENTICATION = "AUTHENTICATION";
export const GET_CONFIGURATION_OVWERVIEW_SUCCESS =
  "GET_CONFIGURATION_OVWERVIEW_SUCCESS";
export const GET_CONFIGURATION_OVWERVIEW_FAIL =
  "GET_CONFIGURATION_OVWERVIEW_FAIL";
export const GET_CONFIGURATION_OVWERVIEW = "GET_CONFIGURATION_OVWERVIEW";
export const CHANGE_ROUTE_ID = "CHANGE_ROUTE_ID";
export const SELECTED_TRIP = "SELECTED_TRIP";
export const GET_TICKET_INFO = "GET_TICKET_INFO";
export const GET_TICKET_INFO_SUCCESS = "GET_TICKET_INFO_SUCCESS";
export const GET_TICKET_INFO_FAIL = "GET_TICKET_INFO_FAIL";
export const BUILD_DATA_RENDER_SEAT_DIAGRAM = "BUILD_DATA_RENDER_SEAT_DIAGRAM";
