export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "FAIL";
export const GET_DAY = "GET_DAY";
export const SELECT_DAY = "SELECT_DAY";
export const NEXT_DAY = "NEXT_DAY";
export const GET_TRIPS = "GET_TRIPS";
export const GET_TRIPS_SUCCESS = "GET_TRIPS_SUCCESS";
export const GET_TRIPS_FAIL = "GET_TRIPS_FAIL";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAIL = "AUTHENTICATION_FAIL";
export const AUTHENTICATION = "AUTHENTICATION";
export const GET_CONFIGURATION_OVWERVIEW_SUCCESS =
  "GET_CONFIGURATION_OVWERVIEW_SUCCESS";
export const GET_CONFIGURATION_OVWERVIEW_FAIL =
  "GET_CONFIGURATION_OVWERVIEW_FAIL";
export const GET_CONFIGURATION_OVWERVIEW = "GET_CONFIGURATION_OVWERVIEW";
export const CHANGE_ROUTE_ID = "CHANGE_ROUTE_ID";
